// <auto-generated />
using System;
using ApiECommerce.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiECommerce.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241014085518_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiECommerce.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "lanches1.png",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "combos1.png",
                            Name = "Combos"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "naturais1.png",
                            Name = "Natural"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "refrigerantes1.png",
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "sucos1.png",
                            Name = "Juices"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "sobremesas1.png",
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("ApiECommerce.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ApiECommerce.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ApiECommerce.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<bool>("BestSeller")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Popular")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            BestSeller = true,
                            CategoryId = 1,
                            Details = "Soft bread, seasoned beef hamburger, onion, mustard, and ketchup ",
                            ImageUrl = "hamburger1.jpeg",
                            Name = "Standard Hamburger",
                            Popular = true,
                            Price = 15m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 1,
                            Details = "Soft bread, seasoned beef hamburger, and cheese all around.",
                            ImageUrl = "hamburger3.jpeg",
                            Name = "Standard Cheeseburger",
                            Popular = true,
                            Price = 18m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 1,
                            Details = "Soft bread, seasoned beef hamburger, onion, lettuce, mustard, and ketchup ",
                            ImageUrl = "hamburger4.jpeg",
                            Name = "Standard Cheese Salad",
                            Popular = false,
                            Price = 19m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 4,
                            Available = false,
                            BestSeller = false,
                            CategoryId = 2,
                            Details = "Soft bread, seasoned beef hamburger and cheese, soda, and fries",
                            ImageUrl = "combo1.jpeg",
                            Name = "Hamburger, fries, soda",
                            Popular = true,
                            Price = 25m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 2,
                            Details = "Soft bread, seasoned beef hamburger, soda, and fries, onion, mayonnaise, and ketchup",
                            ImageUrl = "combo2.jpeg",
                            Name = "Cheeseburger, fries, soda",
                            Popular = false,
                            Price = 27m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 2,
                            Details = "Soft bread, seasoned beef hamburger, soda, and fries, onion, mayonnaise, and ketchup",
                            ImageUrl = "combo3.jpeg",
                            Name = "Cheese Salad, fries, soda",
                            Popular = true,
                            Price = 28m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 3,
                            Details = "Whole grain bread with greens and tomato",
                            ImageUrl = "lanche_natural1.jpeg",
                            Name = "Natural Snack with greens",
                            Popular = false,
                            Price = 14m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 3,
                            Details = "Whole grain bread, greens, tomato, and cheese.",
                            ImageUrl = "lanche_natural2.jpeg",
                            Name = "Natural Snack and cheese",
                            Popular = true,
                            Price = 15m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 9,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 3,
                            Details = "Vegan snack with healthy ingredients",
                            ImageUrl = "lanche_vegano1.jpeg",
                            Name = "Vegan Snack",
                            Popular = false,
                            Price = 25m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 10,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 4,
                            Details = "Coca-Cola soda",
                            ImageUrl = "coca_cola1.jpeg",
                            Name = "Coca-Cola",
                            Popular = true,
                            Price = 21m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 11,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 4,
                            Details = "Guaraná soda",
                            ImageUrl = "guarana1.jpeg",
                            Name = "Guaraná",
                            Popular = false,
                            Price = 25m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 12,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 4,
                            Details = "Pepsi Cola soda",
                            ImageUrl = "pepsi1.jpeg",
                            Name = "Pepsi",
                            Popular = false,
                            Price = 21m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 13,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 5,
                            Details = "Delicious and nutritious orange juice",
                            ImageUrl = "suco_laranja.jpeg",
                            Name = "Orange Juice",
                            Popular = false,
                            Price = 11m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 14,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 5,
                            Details = "Fresh strawberry juice",
                            ImageUrl = "suco_morango1.jpeg",
                            Name = "Strawberry Juice",
                            Popular = false,
                            Price = 15m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 15,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 5,
                            Details = "Natural grape juice without sugar made with the fruit",
                            ImageUrl = "suco_uva1.jpeg",
                            Name = "Grape Juice",
                            Popular = false,
                            Price = 13m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 16,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 4,
                            Details = "Fresh natural mineral water",
                            ImageUrl = "agua_mineral1.jpeg",
                            Name = "Water",
                            Popular = false,
                            Price = 5m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 17,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 6,
                            Details = "Chocolate cookies with chocolate chunks",
                            ImageUrl = "cookie1.jpeg",
                            Name = "Chocolate Cookies",
                            Popular = true,
                            Price = 8m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 18,
                            Available = true,
                            BestSeller = true,
                            CategoryId = 6,
                            Details = "Delicious and crunchy vanilla cookies",
                            ImageUrl = "cookie2.jpeg",
                            Name = "Vanilla Cookies",
                            Popular = false,
                            Price = 8m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 19,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 6,
                            Details = "Swiss pie with cream and layers of dulce de leche",
                            ImageUrl = "torta_suica1.jpeg",
                            Name = "Swiss Pie",
                            Popular = true,
                            Price = 10m,
                            Stock = 10
                        });
                });

            modelBuilder.Entity("ApiECommerce.Entities.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("ApiECommerce.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiECommerce.Entities.Order", b =>
                {
                    b.HasOne("ApiECommerce.Entities.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiECommerce.Entities.OrderDetail", b =>
                {
                    b.HasOne("ApiECommerce.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiECommerce.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApiECommerce.Entities.Product", b =>
                {
                    b.HasOne("ApiECommerce.Entities.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiECommerce.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("ApiECommerce.Entities.Product", null)
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiECommerce.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ApiECommerce.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ApiECommerce.Entities.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ShoppingCartItems");
                });

            modelBuilder.Entity("ApiECommerce.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
